### PR TITLE
Migrate gem to VT api V3.

### PR DESCRIPTION
**Pull request by crondaemon**
Fix: #25.

### CODE REVIEW

**Comment by crondaemon** [comment]
Hey @pwelch have you got the chance to look at the PR?

**Comment by pwelch** [comment]
@crondaemon apologizes! I have it on my to-do list. I will try to go over it in the next few days. Thank you so much again for putting this work in. I'll get it published soon!

**Review by pwelch — APPROVED** [review]
👍 🥳

**Comment by pwelch** [comment]
@crondaemon & @jonnynux 
Released v5.0: https://rubygems.org/gems/virustotal_api/versions/0.5.0

Thank you both for your hard work helping maintain this gem!

**Comment by crondaemon** [comment]
Thanks to you for your responsiveness. We will propose more changes to cover more V3 endpoints (we've cover what was covered in the past, so far). Stay tuned :smiley:.

**Comment by pwelch** [comment]
@crondaemon awesome can't wait!

**Pull request merged**
