### PR TITLE
Add rescan api

### PR DESCRIPTION
**Pull request by jonnynux**
Add file rescan api, so you can request a new rescan for an already present resource.

### CODE REVIEW

**Comment by jonnynux** [comment]
I forgot to add this functionality to the readme. If it's necessary tell me.

**Comment by pwelch** [comment]
Yeah that would help. Thanks!

**Comment by jonnynux** [comment]
I did it.

**Comment by pwelch** [comment]
@jonnynux Thanks! I'll try to get it merged this weekend.

**Comment by pwelch** [comment]
@jonnynux 
- Merged your PRs
- Updated the Contributors and Changelog section to credit you
- Published a new version to Ruby Gems: https://rubygems.org/gems/virustotal_api/versions/0.4.0

Thanks for the PRs! 🍻

**Comment by jonnynux** [comment]
That's great @pwelch, thanks. My pleasure to contribute.

**Pull request merged**
