### PR TITLE
base: use strict_encode in base64 encoding.

### PR DESCRIPTION
**Pull request by crondaemon**
This prevents the newline to cause errors.

### CODE REVIEW

**Comment by jonnynux** [comment]
Hi @pwelch, have you seen this?

Thanks ;)

**Comment by pwelch** [comment]
@jonnynux My apologizes! Somehow I missed this PR notification! 

Changes look good to me! Should I release this or did you want to add more?

**Comment by crondaemon** [comment]
I'd suggest to merge and release asap, since one commit fixes a nasty bug.

**Comment by pwelch** [comment]
@jonnynux  @crondaemon 

Merged and released: https://rubygems.org/gems/virustotal_api/versions/0.5.4

Thank you as always!

**Pull request merged**
