### PR TITLE
Url encoding

### PR DESCRIPTION
**Pull request by jonnynux**
CHANGELOG: Fixed

## Summary
Strict base64 encoder encodes wrongly some chars in `/` that creates misunderstanding. As suggested by python code in the API documentation, it's necessary to replace it with a urlsafe base64 encoder that replaces `/` with `_`.

## Testing

Added a test that retrieves a correct result instead of an empty one.

### CODE REVIEW

**Comment by crondaemon** [comment]
@jonnynux are you sure you want to drop 2.5? I am ok with removing it from github actions, but putting it into the gem spec means no one with legacy ruby will be able to run the gem. EOL doesn't mean necessarily have a domino effect.

**Comment by jonnynux** [comment]
> 
> 
> @jonnynux are you sure you want to drop 2.5? I am ok with removing it from github actions, but putting it into the gem spec means no one with legacy ruby will be able to run the gem. EOL doesn't mean necessarily have a domino effect.

I'm not sure but ruby 2.5 has ended 7 months ago.

**Comment by pwelch** [comment]
I'm okay dropping Ruby 2.5 support for this and future versions. It is EOL and people can use the older version of the gem until they are able to upgrade.

**Comment by jonnynux** [comment]
Otherwise I can split in two different PR.

**Comment by jonnynux** [comment]
@pwelch @crondaemon moved ruby drop in another PR.

**Comment by pwelch** [comment]
@jonnynux @crondaemon Released `v0.5.6` & `v0.5.7`

**Comment by crondaemon** [comment]
Thanks, appreciate.

**Pull request merged**
