### PR TITLE
Add url scan api

### PR DESCRIPTION
**Pull request by jonnynux**

### CODE REVIEW

**Comment by pwelch** [comment]
@jonnynux Awesome! Thank you for contributing back. I'll review this soon.

**Comment by jonnynux** [comment]
I forgot to add this functionality to the readme. If it's necessary tell me.

**Comment by pwelch** [comment]
@jonnynux yeah if you could add it that would be great! Thanks!

**Comment by jonnynux** [comment]
I did it.

**Comment by pwelch** [comment]
Looks good to me! Thanks for the addition to the code!

**Pull request merged**
